# Generated by Django 3.2.25 on 2024-07-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='account_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
