# Generated by Django 3.2.25 on 2024-07-21 23:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20240721_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(default=99999999, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=200)),
                ('type', models.TextField(max_length=20)),
                ('model_number', models.CharField(max_length=10)),
                ('imei', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='devices',
            field=models.ForeignKey(default=000000, on_delete=django.db.models.deletion.CASCADE, to='accounts.device'),
            preserve_default=False,
        ),
    ]
