# Generated by Django 3.2.25 on 2024-07-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20240721_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='account_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
